const models = [
    {
        id: 1,
        name: "bedside",
        imgURL: "bedside.png",
        modelSRC: "bedside/Bedside.gltf",
        iosSRC: "",
        variants: ["Yello", "Mello"],
    },
    {
        id: 2,
        name: "desk",
        imgURL: "desk.png",
        modelSRC: "desk/Desk.gltf",
        iosSRC: "",
        variants: ["Sello"],
    },
    {
        id: 3,
        name: "sofa",
        imgURL: "sofa.png",
        modelSRC: "sofa/Sofa.gltf",
        iosSRC: "",
        variants: [],
    },
    {
        id: 4,
        name: "soda-can",
        imgURL: "soda-can.png",
        modelSRC: "soda-can/Soda-can.gltf",
        iosSRC: "",
        variants: [],
    },
    {
        id: 5,
        name: "plate",
        imgURL: "plate.png",
        modelSRC: "plate/Plate.gltf",
        iosSRC: "",
        variants: [],
    },
    {
        id: 6,
        name: "sink",
        imgURL: "sink.png",
        modelSRC: "sink/Sink.gltf",
        iosSRC: "",
        variants: [],
    },
    {
        id: 7,
        name: "dresser",
        imgURL: "dresser.png",
        modelSRC: "dresser/Dresser.gltf",
        iosSRC: "",
        variants: [],
    },
    {
        id: 8,
        name: "library",
        imgURL: "library.png",
        modelSRC: "library/Library.gltf",
        iosSRC: "",
        variants: [],
    },
    {
        id: 9,
        name: "coffeetable",
        imgURL: "coffeetable.png",
        modelSRC: "coffetable/Coffetable.gltf",
        iosSRC: "",
        variants: [],
    },
  ]

  export default models